### PR TITLE
UHF-399: cookie compliance settings

### PR DESCRIPTION
**Pull request by etrml**
How to test (if you have no setup etc.):
* `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-main hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
* Switch to corresponding branches:
* `composer require drupal/hdbt:dev-UHF-399_EU_cookie_compliance && composer require drupal/helfi_platform_config:dev-UHF-399_EU_cookie_compliance`
* Run `make new`
* Go to site, you should see a popup regarding cookie consent
* Click More info link on popup, you should see the form with category choices on a separate page

Also see related PR's:
https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/26
https://github.com/City-of-Helsinki/drupal-hdbt/pull/34

### CODE REVIEW

**Comment by teroelonen** [comment]
Switching to corresponding branches gives me:
  [Exception]
  Cannot apply patch Helfi-specific customizations to EU Cookie Compliance (./public/modules/cus
  tom/helfi_platform_config/patches/eu_cookie_compliance_block.patch)!

**Comment by teroelonen** [comment]
I got it working on second try - Just wondering if it is supposed to be printed to this node page where there is some testing content?

Screenshot 2021-01-29 at 11 44 13

**Comment by etrml** [comment]
> I got it working on second try - Just wondering if it is supposed to be printed to this node page where there is some testing content?
> 
> Screenshot 2021-01-29 at 11 44 13

Yes. The block is currently automatically appended to node/1, regardless of content.

**Comment by teroelonen** [comment]
There is a story now that has the path addition instead of node/1 https://helsinkiportaali.atlassian.net/browse/UHF-662

**Review by teroelonen — APPROVED** [review]
This gives us the first step to right direction.

**Pull request merged**
